const ASSET_IMAGES = {
  ICON_BOOK_SELECTED: require('../assets/booksSelected.png'),
  ICON_BOOK_UN_SELECTED: require('../assets/booksUnSelected.png'),
  ICON_MY_BOOK_SELECTED: require('../assets/myBookSelected.png'),
  ICON_MY_BOOK_UN_SELECTED: require('../assets/myBookUnSelected.png'),
  ICON_PERSONAL_SELECTED: require('../assets/personalSelected.png'),
  ICON_PERSONAL_UN_SELECT: require('../assets/personalUnSelected.png'),
  ICON_HISTORY: require('../assets/history.png'),
  ICON_SEARCH: require('../assets/iconSearch.png'),
  ICON_DELETE: require('../assets/deleteIcon.png'),
  ICON_RATE_ONE: require('../assets/RateOne.png'),
  ICON_RATE_TWO: require('../assets/RateTwo.png'),
  ICON_RATE_THREE: require('../assets/RateThree.png'),
  ICON_SELECT: require('../assets/iconSelect.png'),
  ICON_SELECTED:require('../assets/iconSelected.png'),
  ICON_ARROW_RIGHT: require('../assets/iconArrowRight.png'),
  ICON_BACK: require('../assets/iconBack.png'),
  ICON_BOOK_ADD: require('../assets/iconBookAdd.png'),
  ICON_MENU_BUTTON: require('../assets/menuButton.png'),
  ICON_CONTENT_SET_BUTTON: require('../assets/contentSet.png'),
  ICON_BRIGHT: require('../assets/bright.png'),
  ICON_ARROW_LEFT: require('../assets/arrowLeft.png'),
  ICON_ADD: require('../assets/iconAdd.png'),
}

export default ASSET_IMAGES